implement WorkspaceFinder
aspect-build/aspect-cli pull request #79
Opened 2021-11-23 21:57 UTC by cvarier

- Introduce `pkg/pathutils/pathutils.go` with `WorskpaceFinder`
- In a subsequent PR, will remove the corresponding method from `bazelisk.go` and refactor `build`, `test`, `clean`, `info` commands to use `InvokeCmdInsideWorkspace`

2021-11-23 22:43 UTC, f0rmiga requested changes

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +*/
```suggestion
/*
Copyright © 2021 Aspect Build Systems Inc

Not licensed for re-use.
*/
```

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +*/
This is just to match the rest of the files we have in the repo.

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +type RunFn func(cmd *cobra.Command, args []string) (exitErr error)
```suggestion
// RunFn is the function signature for the cobra RunE function in the cobra.Command.
type RunFn func(cmd *cobra.Command, args []string) (exitErr error)
```

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +func InvokeCmdInsideWorkspace(toRun RunFn) (wrapped RunFn) {
```suggestion
// InvokeCmdInsideWorkspace verifies if the current working directory is inside a Bazel workspace, then invokes the provided toRun function.
func InvokeCmdInsideWorkspace(toRun RunFn) RunFn {
```

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +func InvokeCmdInsideWorkspace(toRun RunFn) (wrapped RunFn) {
I also removed the named return argument `wrapped` since we don't use it as a named arg.

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +	osGetwd func() (string, error)
You don't need this since the working directory is being passed as an argument to `Find`.

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +// WorkspaceFinder is the interface that wraps the simple Find method that performs the
The comment here is wrong. It's not an interface.

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +// NewDefaultWorkspaceFinder instantiates a default internal implementation of the WorkspaceFinder
It's not an internal implementation since the `WorkspaceFinder` is an exported struct (WorkspaceFinder vs workspaceFinder).

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils.go
> +// is not a Bazel workspace.
```suggestion
// Find tries to find a file that marks the root of a Bazel workspace (WORKSPACE or WORKSPACE.bazel). If the returned
// path is empty and no error was produced, the user's current working directory
// is not a Bazel workspace.
```

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils_test.go
> +package pathutils
Missing license header.

2021-11-23 22:43 UTC, f0rmiga commented on pkg/pathutils/pathutils_test.go
> +func TestInvokeCmdInsideWorkspace(t *testing.T) {
This was supposed to be a unit test, not an integration test. Performing disk IO operations with fixtures is not what we want in the `pkg` sub-packages.

To properly test the logic without calling `os.Stat` and `os.Getwd`, you will need to mock them.

2021-11-23 22:53 UTC, cvarier commented on .gitignore
> +/Library
I think my unit test is doing that when I set $HOME temporarily

2021-11-23 22:59 UTC, f0rmiga commented on .gitignore
> +/Library
Yeah, that testing is bad. We want to do proper integration tests, but not this way.

2021-11-23 22:59 UTC, f0rmiga commented on .gitignore
> +/Library
Revert this change, please. You can keep `/.ijwb`, which I believe is from intellij?

2021-11-24 22:27 UTC, f0rmiga requested changes

2021-11-24 22:27 UTC, f0rmiga commented on pkg/pathutils/pathutils_test.go
> +		RunE: invokeCmdInsideWorkspace(
Don't worry about trying to integrate with the user. From a unit test perspective, you don't care who your user is, you only care that the unitary logic behaves correctly with the input that you allow to be passed.

The tests should be split into 2 top-level `Test*` functions:
- TestWorkspaceFinder - you will mock the `osStat` to make it fail and assert that the `Find` method fails as expected, and play with the various possible `cwd` strings that could be passed to the `Find` method under ideal circumstances.
- TestInvokeInsideWorkspace - you will have to pass the `cobra.Command` to the returned function, which you will call it, but you will not assert that the `cmd` gets called. You will have to assert that the `cmd` gets passed to the `toRun`, though. You will never use the `defaultWorkspaceFinder` on your tests. You can create a `mock` directory and use the same pattern we've been using for other packages using [gomock](https://github.com/golang/mock).

2021-12-11 03:22 UTC, closed without merging